In [1]:

import pandas as pd
df=pd.read_csv('C:/Users/Roshan/SNLP/IMDB Dataset.csv')

# Task 1

In [2]:
df.head(10)
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

# Task 2 Transforming  Document and Vectorize

In [3]:

import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count=CountVectorizer()#intialize CountVectorizer

docs=np.array(['The sun is shinning',
               'The weather is sweet',
              'The sun is shinning ,The weather is sweet, one and one is two'])
bag=count.fit_transform(docs)
print(count.vocabulary_)
print(bag.toarray())

{'the': 6, 'sun': 4, 'is': 1, 'shinning': 3, 'weather': 8, 'sweet': 5, 'one': 2, 'and': 0, 'two': 7}
[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [1 3 2 1 1 1 2 1 1]]


# Task 3 Term Frequency and Inverse Document Frequency

In [4]:

#Term frequencies alone do not contribute to distinct information
#tf-idf (t,d) = tf(t,d) X idf(t,d)
#idf(t,d) = log(nd / 1 + df(d,t))
#where nd = total number of documents and df(d,t) = number of documents that contain the term t

# TASK 4 Feature Extraction

In [5]:

from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer(use_idf=True, norm='l2', smooth_idf=True)

print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

np.set_printoptions(precision=2)
print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[0.         0.43370786 0.         0.55847784 0.55847784 0.
  0.43370786 0.         0.        ]
 [0.         0.43370786 0.         0.         0.         0.55847784
  0.43370786 0.         0.55847784]
 [0.27898205 0.49431387 0.55796409 0.21217304 0.21217304 0.21217304
  0.32954258 0.27898205 0.21217304]]
[[0.   0.43 0.   0.56 0.56 0.   0.43 0.   0.  ]
 [0.   0.43 0.   0.   0.   0.56 0.43 0.   0.56]
 [0.28 0.49 0.56 0.21 0.21 0.21 0.33 0.28 0.21]]


# task 5 Tokenize

In [6]:

from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()

def stemmer_tokenize(text):
    return [porter.stem(word) for word in text.split()]

stemmer_tokenize('coders like coding and thus they code')

['coder', 'like', 'code', 'and', 'thu', 'they', 'code']

# TASK 6

In [7]:

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer(strip_accents=None,
                     lowercase=False,
                     tokenizer=stemmer_tokenize,
                     use_idf=True,
                     norm='l2',
                     smooth_idf=True)
y=df.sentiment.values
x=tfidf.fit_transform(df.review)

# TASK 7  Sentiment Classication using Logistic Regression

In [8]:

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=1, test_size=0.5, shuffle=False)

import pickle

from sklearn.linear_model import LogisticRegressionCV

#model 
clf = LogisticRegressionCV(cv = 5,
                           scoring = 'accuracy',
                           random_state = 0,
                           n_jobs = -3,
                           verbose =3,
                           max_iter = 300).fit(x_train,y_train)

#saving the model 
saved_model=open('saved_model.sav', 'wb')

#using the pickle Library's dump function to write the trained classifier

pickle.dump(clf, saved_model)
saved_model.close()




[Parallel(n_jobs=-3)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-3)]: Done   5 out of   5 | elapsed:  9.1min finished


# Task 8 Model Evaluation

In [9]:
filename = 'saved_model.sav'
saved_clf = pickle.load(open(filename, 'rb'))

saved_clf.score(x_test, y_test)

#saved_model=open('saved_model.sav','wb')
#pickle.dump(clf,saved_model)


C:\Users\Roshan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:2257: ChangedBehaviorWarning: The long-standing behavior to use the accuracy score has changed. The scoring parameter is now used. This warning will disappear in version 0.22.
  ChangedBehaviorWarning)


0.8898